name: aws-eventbridge-action
description: Publish an event to AWS EventBridge.
author: Articulate Global, LLC
inputs:
  event-bus-name:
    required: true
    description: The name or ARN of the event bus to recieve the event.
  source:
    required: true
    description: The source of the event.
  resources:
    required: false
    description: A comma seperated list of of ARNs which the event concerns.
  detail-type:
    required: true
    description: Used to decide what fields to expect in the event detail.
  detail:
    required: true
    description: A valid JSON string.
  aws-region:
    required: true
    description: AWS region
    default: us-east-1
outputs:
  event-id:
    description: The event ID from AWS EventBridge.
runs:
  using: node16
  main: dist/index.js
branding:
  color: blue
  icon: upload-cloud
